spring.datasource.url=jdbc:postgresql://localhost:5432/telegram_bot_db
spring.datasource.username=postgres
spring.datasource.password=Admin
spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

logging.level.liquibase=DEBUG
logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG

telegram.bot.token=8726606813:AAGWbvPqjnhm0S3Rx73wCVnpj_qIUtl6RqM

