spring.datasource.url=jdbc:postgresql://localhost:5432/telegram_bot_db
spring.datasource.username=postgres
spring.datasource.password=Admin
spring.jpa.hibernate.ddl-auto=validate

telegram.bot.token=8726606813:AAGWbvPqjnhm0S3Rx73wCVnpj_qIUtl6RqM

